### ISSUE TITLE
Can scm (dev) dependencies be installed before running tests?

### ISSUE THREAD

**Issue by mikavilpas** [nvim-neorocks/nvim-busted-action#4]
Hi! I'm using this action in my project, and am working on a new feature - I'm adding more robust LSP integration  (https://github.com/mikavilpas/yazi.nvim/pull/190). To do this, I need to add a dependency to this rock: https://luarocks.org/modules/neorocks/nvim-lsp-file-operations

Looks like that rock specifies an `scm` version - I take this to mean "source control management" aka the latest, bleeding edge version. Installing this seems to result in

> Run luarocks test --local
> Missing dependencies for yazi.nvim scm-1:
>   nvim-lsp-file-operations >= scm (not installed)
>
> yazi.nvim scm-1 depends on lua >= 5.1 (5.1-1 provided by VM: success)
> yazi.nvim scm-1 depends on plenary.nvim (scm-1 installed: success)
> yazi.nvim scm-1 depends on nvim-lsp-file-operations >= scm (not installed)
>
> Error: Could not satisfy dependency nvim-lsp-file-operations >= scm: No results matching query were found for Lua 5.1.
> Error: Process completed with exit code 1.
>
> https://github.com/mikavilpas/yazi.nvim/actions/runs/9925762312/job/27418523508#step:6:157

I'm not too familiar with luarocks, so any help would be appreciated.

**Comment by mrcjkb** [comment]
Hey :wave: 

I'd have to add support for something like a `extra_luarocks_args` input to this action (which I likely won't have time for until after Thursday).
You should be able to run tests locally by adding the `--dev` flag to `luarocks test`.

**Comment by mrcjkb** [comment]
If you need to depend on `scm` packages, you can now install them manually, as follows:

```yaml
   - name: Run tests
     uses: nvim-neorocks/nvim-busted-action@v1
     with:
       before: |
         # bash script to run before tests
         luarocks install --dev --local nvim-lsp-file-operations
```
